"""bpost_address_validator

Python wrapper for bpost External Mailing Address Proofing API.

Sync and async clients using httpx and Pydantic models.
"""

from .client import BpostClient, AsyncBpostClient
from .models import (
    AddressToValidate,
    AddressToValidateList,
    AddressBlockLines,
    UnstructuredAddressLineItem,
    PostalAddress,
    DeliveryPointLocation,
    StructuredDeliveryPointLocation,
    PostalCodeMunicipality,
    StructuredPostalCodeMunicipality,
    OtherDeliveryInformation,
    StructuredOtherDeliveryInformation,
    ValidateAddressesRequestContent,
    ValidateAddressOptions,
    CallerIdentification,
    ValidateAddressesRequest,
    GeoCoordinate,
    GeographicalLocation,
    GeographicalLocationInfo,
    ServicePointDetailInfo,
    NisCodeInfo,
    NisNameItem,
    NisHierarchyResultItem,
    NisHierarchyInfo,
    ServicePointResultItem,
    ServicePointBoxListInfo,
    ServicePointSuffixListInfo,
    FormattedAddress,
    ValidatedAddress,
    ValidatedAddressResult,
    ValidatedAddressResultList,
    ValidateAddressesResponse,
    ValidationErrorItem,
    AddressFields,
    ValidatedAddressFields,
    AddressResultFields,
    GeoLocation,
    LocalizedName,
    NisHierarchyEntry,
    ServicePointNumbers,
)
from .errors import ApiError
from .helpers import (
    ValidationPresets,
    create_structured_address,
    create_unstructured_address,
    create_address_to_validate,
    create_simple_request,
    create_batch_request,
    extract_address_fields,
    extract_from_validated_address,
    extract_from_result,
    extract_label_lines,
    extract_all_results,
    extract_geo_location,
    extract_nis_code,
    extract_nis_hierarchy,
    extract_box_list,
    extract_suffix_list,
    extract_submitted_address_lines,
)

__all__ = [
    # Clients
    "BpostClient",
    "AsyncBpostClient",
    # Models
    "AddressToValidate",
    "AddressToValidateList",
    "AddressBlockLines",
    "UnstructuredAddressLineItem",
    "PostalAddress",
    "DeliveryPointLocation",
    "StructuredDeliveryPointLocation",
    "PostalCodeMunicipality",
    "StructuredPostalCodeMunicipality",
    "OtherDeliveryInformation",
    "StructuredOtherDeliveryInformation",
    "ValidateAddressesRequestContent",
    "ValidateAddressOptions",
    "CallerIdentification",
    "ValidateAddressesRequest",
    "GeoCoordinate",
    "GeographicalLocation",
    "GeographicalLocationInfo",
    "ServicePointDetailInfo",
    "NisCodeInfo",
    "NisNameItem",
    "NisHierarchyResultItem",
    "NisHierarchyInfo",
    "ServicePointResultItem",
    "ServicePointBoxListInfo",
    "ServicePointSuffixListInfo",
    "FormattedAddress",
    "ValidatedAddress",
    "ValidatedAddressResult",
    "ValidatedAddressResultList",
    "ValidateAddressesResponse",
    "ValidationErrorItem",
    # Extraction result types
    "AddressFields",
    "ValidatedAddressFields",
    "AddressResultFields",
    "GeoLocation",
    "LocalizedName",
    "NisHierarchyEntry",
    "ServicePointNumbers",
    # Errors
    "ApiError",
    # Helpers
    "ValidationPresets",
    "create_structured_address",
    "create_unstructured_address",
    "create_address_to_validate",
    "create_simple_request",
    "create_batch_request",
    "extract_address_fields",
    "extract_from_validated_address",
    "extract_from_result",
    "extract_label_lines",
    "extract_all_results",
    "extract_geo_location",
    "extract_nis_code",
    "extract_nis_hierarchy",
    "extract_box_list",
    "extract_suffix_list",
    "extract_submitted_address_lines",
]
